let arr=[{
    "id":31,
    "urlSlug":"anshika-saxena",
    "namePrefix":null,
    "firstName":"anshika",
    "lastName":"saxena",
    "aboutMe":"Hello I am here",
    "profliePicUrl":null,
    "experience":1.0,
    "languages":[
       
    ],
    "minimumCallDuration":5,
    "minimumCallDurationCharges":50.0,
    "additionalPerMinuteCharges":10.0,
    "isAvailable":true,
    "rating":5.0,
    "skills":[
       
    ],
    "isOnCall":false,
    "images":{
       "large":{
          "imageUrl":"",
          "id":92
       },
       "medium":{
          "imageUrl":"https://tak-astrotak-av-dev.s3.ap-south-1.amazonaws.com/astro-images/agents/1.png",
          "id":123
       }
    },
    "availability":{
       "days":[
          "MON",
          "WED",
          "THU",
          "FRI"
       ],
       "slot":{
          "toFormat":"PM",
          "fromFormat":"AM",
          "from":"10",
          "to":"7"
       }
    }
 },{
    "id":31,
    "urlSlug":"anshika-saxena",
    "namePrefix":null,
    "firstName":"arvind",
    "lastName":"shukla",
    "aboutMe":"Hello I am here",
    "profliePicUrl":null,
    "experience":1.0,
    "languages":[
       
    ],
    "minimumCallDuration":5,
    "minimumCallDurationCharges":50.0,
    "additionalPerMinuteCharges":10.0,
    "isAvailable":true,
    "rating":null,
    "skills":[
       
    ],
    "isOnCall":false,
    "images":{
       "large":{
          "imageUrl":"",
          "id":92
       },
       "medium":{
          "imageUrl":"https://tak-astrotak-av-dev.s3.ap-south-1.amazonaws.com/astro-images/agents/1.png",
          "id":123
       }
    },
    "availability":{
       "days":[
          "MON",
          "WED",
          "THU",
          "FRI"
       ],
       "slot":{
          "toFormat":"PM",
          "fromFormat":"AM",
          "from":"10",
          "to":"7"
       }
    }
 },{
    "id":31,
    "urlSlug":"anshika-saxena",
    "namePrefix":null,
    "firstName":"ashwani",
    "lastName":"mangal",
    "aboutMe":"Hello I am here",
    "profliePicUrl":null,
    "experience":1.0,
    "languages":[
       
    ],
    "minimumCallDuration":5,
    "minimumCallDurationCharges":50.0,
    "additionalPerMinuteCharges":10.0,
    "isAvailable":true,
    "rating":null,
    "skills":[
       
    ],
    "isOnCall":false,
    "images":{
       "large":{
          "imageUrl":"",
          "id":92
       },
       "medium":{
          "imageUrl":"https://tak-astrotak-av-dev.s3.ap-south-1.amazonaws.com/astro-images/agents/1.png",
          "id":123
       }
    },
    "availability":{
       "days":[
          "MON",
          "WED",
          "THU",
          "FRI"
       ],
       "slot":{
          "toFormat":"PM",
          "fromFormat":"AM",
          "from":"10",
          "to":"7"
       }
    }
 },{
    "id":31,
    "urlSlug":"anshika-saxena",
    "namePrefix":null,
    "firstName":"sripati",
    "lastName":"tripati",
    "aboutMe":"Hello I am here",
    "profliePicUrl":null,
    "experience":1.0,
    "languages":[
       
    ],
    "minimumCallDuration":5,
    "minimumCallDurationCharges":50.0,
    "additionalPerMinuteCharges":10.0,
    "isAvailable":true,
    "rating":null,
    "skills":[
       
    ],
    "isOnCall":false,
    "images":{
       "large":{
          "imageUrl":"",
          "id":92
       },
       "medium":{
          "imageUrl":"https://tak-astrotak-av-dev.s3.ap-south-1.amazonaws.com/astro-images/agents/1.png",
          "id":123
       }
    },
    "availability":{
       "days":[
          "MON",
          "WED",
          "THU",
          "FRI"
       ],
       "slot":{
          "toFormat":"PM",
          "fromFormat":"AM",
          "from":"10",
          "to":"7"
       }
    }
 },{
    "id":31,
    "urlSlug":"anshika-saxena",
    "namePrefix":null,
    "firstName":"acharya arvind",
    "lastName":"mishra",
    "aboutMe":"Hello I am here",
    "profliePicUrl":null,
    "experience":1.0,
    "languages":[
       
    ],
    "minimumCallDuration":5,
    "minimumCallDurationCharges":50.0,
    "additionalPerMinuteCharges":10.0,
    "isAvailable":true,
    "rating":null,
    "skills":[
       
    ],
    "isOnCall":false,
    "images":{
       "large":{
          "imageUrl":"",
          "id":92
       },
       "medium":{
          "imageUrl":"https://tak-astrotak-av-dev.s3.ap-south-1.amazonaws.com/astro-images/agents/1.png",
          "id":123
       }
    },
    "availability":{
       "days":[
          "MON",
          "WED",
          "THU",
          "FRI"
       ],
       "slot":{
          "toFormat":"PM",
          "fromFormat":"AM",
          "from":"10",
          "to":"7"
       }
    }
 },{
    "id":31,
    "urlSlug":"anshika-saxena",
    "namePrefix":null,
    "firstName":"mahajan",
    "lastName":"tripati",
    "aboutMe":"Hello I am here",
    "profliePicUrl":null,
    "experience":1.0,
    "languages":[
       
    ],
    "minimumCallDuration":5,
    "minimumCallDurationCharges":50.0,
    "additionalPerMinuteCharges":10.0,
    "isAvailable":true,
    "rating":null,
    "skills":[
       
    ],
    "isOnCall":false,
    "images":{
       "large":{
          "imageUrl":"",
          "id":92
       },
       "medium":{
          "imageUrl":"https://tak-astrotak-av-dev.s3.ap-south-1.amazonaws.com/astro-images/agents/1.png",
          "id":123
       }
    },
    "availability":{
       "days":[
          "MON",
          "WED",
          "THU",
          "FRI"
       ],
       "slot":{
          "toFormat":"PM",
          "fromFormat":"AM",
          "from":"10",
          "to":"7"
       }
    }
 },{
    "id":31,
    "urlSlug":"anshika-saxena",
    "namePrefix":null,
    "firstName":"yogita",
    "lastName":"purohit",
    "aboutMe":"Hello I am here",
    "profliePicUrl":null,
    "experience":1.0,
    "languages":[
       
    ],
    "minimumCallDuration":5,
    "minimumCallDurationCharges":50.0,
    "additionalPerMinuteCharges":10.0,
    "isAvailable":true,
    "rating":null,
    "skills":[
       
    ],
    "isOnCall":false,
    "images":{
       "large":{
          "imageUrl":"",
          "id":92
       },
       "medium":{
          "imageUrl":"https://tak-astrotak-av-dev.s3.ap-south-1.amazonaws.com/astro-images/agents/1.png",
          "id":123
       }
    },
    "availability":{
       "days":[
          "MON",
          "WED",
          "THU",
          "FRI"
       ],
       "slot":{
          "toFormat":"PM",
          "fromFormat":"AM",
          "from":"10",
          "to":"7"
       }
    }
 },{
    "id":31,
    "urlSlug":"anshika-saxena",
    "namePrefix":null,
    "firstName":"raman",
    "lastName":"saxena",
    "aboutMe":"Hello I am here",
    "profliePicUrl":null,
    "experience":1.0,
    "languages":[
       
    ],
    "minimumCallDuration":5,
    "minimumCallDurationCharges":50.0,
    "additionalPerMinuteCharges":10.0,
    "isAvailable":true,
    "rating":null,
    "skills":[
       
    ],
    "isOnCall":false,
    "images":{
       "large":{
          "imageUrl":"",
          "id":92
       },
       "medium":{
          "imageUrl":"https://tak-astrotak-av-dev.s3.ap-south-1.amazonaws.com/astro-images/agents/1.png",
          "id":123
       }
    },
    "availability":{
       "days":[
          "MON",
          "WED",
          "THU",
          "FRI"
       ],
       "slot":{
          "toFormat":"PM",
          "fromFormat":"AM",
          "from":"10",
          "to":"7"
       }
    }
 }]
 module.exports=function(){
     return arr;
 }